-- 코드를 작성해주세요
WITH A AS (
    SELECT ID, PARENT_ID
    FROM ECOLI_DATA
    )
SELECT E.ID, count(A.ID) AS CHILD_COUNT
FROM ECOLI_DATA AS E
LEFT JOIN A 
ON E.ID = A.PARENT_ID
GROUP BY E.ID
ORDER BY E.ID ASC

    