-- 코드를 작성해주세요
WITH PERCENT AS (
    SELECT ID, PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS PER
    FROM ECOLI_DATA
)

SELECT E.ID, 
CASE 
WHEN P.PER <= 0.25 
THEN 'CRITICAL'
WHEN P.PER <= 0.5
THEN 'HIGH'
WHEN P.PER <= 0.75
THEN 'MEDIUM'
ELSE 'LOW'
END AS COLONY_NAME
FROM ECOLI_DATA AS E
INNER JOIN PERCENT AS P 
ON E.ID = P.ID
ORDER BY ID ASC