-- 코드를 입력하세요
-- left side에 ANIMAL_OUTS를 두고  right side에 ANIMAL_INS를 둠
SELECT O.ANIMAL_ID, O.NAME
FROM ANIMAL_OUTS AS O
LEFT JOIN ANIMAL_INS AS I
ON O.ANIMAL_ID = I.ANIMAL_ID
WHERE I.ANIMAL_ID IS NULL
# ORDER BY
