-- 코드를 작성해주세요
SELECT ROUTE, CONCAT(ROUND(SUM(D_BETWEEN_DIST),1), 'km') AS TOTAL_DISTANCE, CONCAT(ROUND(AVG(D_BETWEEN_DIST),2), 'km') AS AVERAGE_DISTANCE
FROM SUBWAY_DISTANCE
GROUP BY ROUTE
# ORDER BY TOTAL_DISTANCE DESC -- 이렇게 하면 문자열을 정렬하는 거라서 오류가 나는듯
ORDER BY SUM(D_BETWEEN_DIST) DESC