-- 코드를 작성해주세요
SELECT ROUTE, 
CONCAT(ROUND(SUM(D_BETWEEN_DIST),1),'km') AS TOTAL_DISTANCE, 
CONCAT(ROUND(AVG(D_BETWEEN_DIST),2),'km') AS AVERAGE_DISTANCE
FROM SUBWAY_DISTANCE
GROUP BY ROUTE
# ORDER BY TOTAL_DISTANCE DESC // concat으로 문자열을 만들었기 때문에 제대로 정렬이 안됨
ORDER BY ROUND(SUM(D_BETWEEN_DIST),1) DESC;
