-- 코드를 입력하세요
SELECT F.FLAVOR
FROM FIRST_HALF AS F
INNER JOIN JULY AS J 
ON F.FLAVOR = J.FLAVOR
GROUP BY F.FLAVOR
ORDER BY (SUM(J.TOTAL_ORDER) + SUM(F.TOTAL_ORDER)) DESC
# SUM(J.TOTAL_ORDER)는 JULY 테이블에서 각 FLAVOR에 대해 총 주문량을 계산
# SUM(F.TOTAL_ORDER)는 FIRST_HALF 테이블에서 각 FLAVOR에 대해 총 주문량을 계산
LIMIT 3