-- 코드를 작성해주세요
SELECT T.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_INFO AS I
INNER JOIN ITEM_TREE AS T
ON I.ITEM_ID = T.ITEM_ID
# WHERE T.PARENT_ITEM_ID IS NOT NULL AND I.RARITY = 'RARE' -- 이렇게 하면 자식의 희귀도를 찾지 못함?
WHERE T.PARENT_ITEM_ID IN (SELECT ITEM_ID
                          FROM ITEM_INFO
                          WHERE RARITY = 'RARE')
ORDER BY T.ITEM_ID DESC
