-- 코드를 작성해주세요
-- 자기의 GENOTYPE에 부모의 GENOTYPE을 & 해서 부모 GENOTYPE이 나오면 됨!! (0이 아닌게 아님)
WITH PARENT_TABLE AS ( 
     SELECT ID, GENOTYPE
     FROM ECOLI_DATA ) 
     
SELECT E.ID, E.GENOTYPE, P.GENOTYPE AS PARENT_GENOTYPE -- 부모대장균의 형질 가지고 오기 확인해보려면 ,P.ID AS PARENT_ID 추가  
FROM ECOLI_DATA AS E
INNER JOIN PARENT_TABLE AS P
ON E.PARENT_ID = P.ID -- 원 테이블의 부모 아이디와 새로 만든 테이블의 ID가 같음 
WHERE E.GENOTYPE & P.GENOTYPE = P.GENOTYPE
ORDER BY E.ID ASC