-- 코드를 작성해주세요
SELECT YEAR(E.DIFFERENTIATION_DATE) AS YEAR, M.MAX_SIZE_OF_COLONY - E.SIZE_OF_COLONY AS YEAR_DEV, E.ID
FROM ECOLI_DATA AS E, (SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE_OF_COLONY 
                      FROM ECOLI_DATA
                      GROUP BY YEAR(DIFFERENTIATION_DATE)) M
WHERE YEAR(E.DIFFERENTIATION_DATE) = M.YEAR
ORDER BY YEAR(E.DIFFERENTIATION_DATE) ASC, YEAR_DEV ASC
