-- 코드를 작성해주세요
WITH GRADE AS(
    SELECT EMP_NO, SUM(SCORE) AS SCORE, YEAR
    FROM HR_GRADE
    WHERE YEAR = 2022
    GROUP BY EMP_NO)
    
SELECT G.SCORE, E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM HR_EMPLOYEES AS E
INNER JOIN GRADE AS G
ON E.EMP_NO = G.EMP_NO
ORDER BY G.SCORE DESC
LIMIT 1
