-- 코드를 입력하세요
SELECT B.TITLE, R.BOARD_ID, R.REPLY_ID, R.WRITER_ID, R.CONTENTS, DATE_FORMAT(R.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_REPLY R
INNER JOIN USED_GOODS_BOARD B
ON B.BOARD_ID = R.BOARD_ID
# WHERE DATE_FORMAT(R.CREATED_DATE, '%M') = 10
# WHERE R.CREATED_DATE LIKE '%10%'
WHERE B.CREATED_DATE LIKE '2022-10%'
ORDER BY R.CREATED_DATE ASC, B.TITLE ASC