-- 코드를 입력하세요
# WITH MAX_VIEW AS (
#     SELECT BOARD_ID
#     FROM USED_GOODS_BOARD
#     WHERE VIEWS = MAX(VIEWS)
# )

SELECT CONCAT('/home/grep/src/',F.BOARD_ID,'/',F.FILE_ID,F.FILE_NAME,F.FILE_EXT) AS FILE_PATH
# MAX(B.VIEWS) AS MAXVIEW
FROM USED_GOODS_FILE AS F
INNER JOIN USED_GOODS_BOARD AS B
ON B.BOARD_ID = F.BOARD_ID
WHERE B.VIEWS IN (SELECT MAX(VIEWS)
               FROM USED_GOODS_BOARD
               )
ORDER BY F.FILE_ID DESC;