-- 코드를 작성해주세요
WITH AVG_LENGTH AS (
    SELECT AVG(IFNULL(LENGTH,10))AS LENGTH, FISH_TYPE
    # SELECT AVG(CASE WHEN LENGTH IS NULL THEN 10 ELSE LENGTH END) AS LENGTH, FISH_TYPE
    FROM FISH_INFO
    GROUP BY FISH_TYPE)


SELECT count(F.ID) AS FISH_COUNT, 
MAX(F.LENGTH) AS MAX_LENGTH, F.FISH_TYPE
# MAX(CASE WHEN F.LENGTH IS NULL THEN 10 ELSE F.LENGTH END) AS MAX_LENGTH, F.FISH_TYPE
FROM FISH_INFO AS F
INNER JOIN AVG_LENGTH AS A
ON A.FISH_TYPE = F.FISH_TYPE
WHERE A.LENGTH >= 33
GROUP BY F.FISH_TYPE
ORDER BY F.FISH_TYPE ASC