-- 코드를 입력하세요
SELECT B.BOOK_ID, A.AUTHOR_NAME, DATE_FORMAT(B.PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK AS B
INNER JOIN AUTHOR AS A
ON B.AUTHOR_ID = A.AUTHOR_ID
WHERE (B.AUTHOR_ID, B.CATEGORY) IN (SELECT AUTHOR_ID, CATEGORY
                                   FROM BOOK
                                   WHERE CATEGORY='경제')
ORDER BY PUBLISHED_DATE ASC;
